//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nooch.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nooch.Common.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br/&gt;.
        /// </summary>
        public static string BREAK {
            get {
                return ResourceManager.GetString("BREAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string COMMA_WITH_SINGLE_SPACE {
            get {
                return ResourceManager.GetString("COMMA_WITH_SINGLE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicTemlatesPath.
        /// </summary>
        public static string CONFIG_KEY_DYNAMICTEMPLATES_PATH {
            get {
                return ResourceManager.GetString("CONFIG_KEY_DYNAMICTEMPLATES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailTemplatesPath.
        /// </summary>
        public static string CONFIG_KEY_EMAILTEMPLATES_PATH {
            get {
                return ResourceManager.GetString("CONFIG_KEY_EMAILTEMPLATES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DBACTION_DELETE {
            get {
                return ResourceManager.GetString("DBACTION_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string DBACTION_INSERT {
            get {
                return ResourceManager.GetString("DBACTION_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string DBACTION_UPDATE {
            get {
                return ResourceManager.GetString("DBACTION_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string DISPUTE_STATUS_REPORTED {
            get {
                return ResourceManager.GetString("DISPUTE_STATUS_REPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string DISPUTE_STATUS_RESOLVED {
            get {
                return ResourceManager.GetString("DISPUTE_STATUS_RESOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under Review.
        /// </summary>
        public static string DISPUTE_STATUS_REVIEW {
            get {
                return ResourceManager.GetString("DISPUTE_STATUS_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string EAGER_LOAD_LIMIT {
            get {
                return ResourceManager.GetString("EAGER_LOAD_LIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityObject.
        /// </summary>
        public static string ENTITY_OBJECT {
            get {
                return ResourceManager.GetString("ENTITY_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityReference.
        /// </summary>
        public static string ENTITY_REFERENCE {
            get {
                return ResourceManager.GetString("ENTITY_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 188975311151047.
        /// </summary>
        public static string FACEBOOK_APP_CLIENTID {
            get {
                return ResourceManager.GetString("FACEBOOK_APP_CLIENTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c813e8a5d3813d841b333a59f5ba09d8.
        /// </summary>
        public static string FACEBOOK_APP_SECRETKEY {
            get {
                return ResourceManager.GetString("FACEBOOK_APP_SECRETKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;$LINK_URL$&quot; $ATTRIBUTES$&gt;$LINK_TEXT$&lt;/a&gt;.
        /// </summary>
        public static string INNER_HTML {
            get {
                return ResourceManager.GetString("INNER_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Memo$.
        /// </summary>
        public static string MEMO {
            get {
                return ResourceManager.GetString("MEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string ONE {
            get {
                return ResourceManager.GetString("ONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Cents$.
        /// </summary>
        public static string PLACEHLODER_CENTS {
            get {
                return ResourceManager.GetString("PLACEHLODER_CENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NoochAdmin$.
        /// </summary>
        public static string PLACEHOLDER_ADMIN_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_ADMIN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $AppstoreLogo$.
        /// </summary>
        public static string PLACEHOLDER_APPSTORE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_APPSTORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $AccountNumber$.
        /// </summary>
        public static string PLACEHOLDER_BANK_ACCOUNT_NUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_BANK_ACCOUNT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Amount$.
        /// </summary>
        public static string PLACEHOLDER_BANK_BALANCE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_BANK_BALANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $BankName$.
        /// </summary>
        public static string PLACEHOLDER_BANK_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_BANK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Date$.
        /// </summary>
        public static string PLACEHOLDER_DATE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $DisputeId$.
        /// </summary>
        public static string PLACEHOLDER_DISPUTEID {
            get {
                return ResourceManager.GetString("PLACEHOLDER_DISPUTEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ExistingUser$.
        /// </summary>
        public static string PLACEHOLDER_EXISTINGUSER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_EXISTINGUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FirstName$.
        /// </summary>
        public static string PLACEHOLDER_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FriendFirstName$.
        /// </summary>
        public static string PLACEHOLDER_FRIEND_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_FRIEND_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FriendLastName$.
        /// </summary>
        public static string PLACEHOLDER_FRIEND_LAST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_FRIEND_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $LastName$.
        /// </summary>
        public static string PLACEHOLDER_LAST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Amount$.
        /// </summary>
        public static string PLACEHOLDER_LOWBALANCE_AMOUNT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_LOWBALANCE_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NewUser$.
        /// </summary>
        public static string PLACEHOLDER_NEWUSER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NEWUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NoochHomePage$.
        /// </summary>
        public static string PLACEHOLDER_NOOCHHOMEPAGE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NOOCHHOMEPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NoochLogo$.
        /// </summary>
        public static string PLACEHOLDER_NOOCHLOGO {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NOOCHLOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Notes$.
        /// </summary>
        public static string PLACEHOLDER_NOTES {
            get {
                return ResourceManager.GetString("PLACEHOLDER_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Other_Link$.
        /// </summary>
        public static string PLACEHOLDER_OTHER_LINK {
            get {
                return ResourceManager.GetString("PLACEHOLDER_OTHER_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $PackageName$.
        /// </summary>
        public static string PLACEHOLDER_PACKAGENAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PACKAGENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Package$.
        /// </summary>
        public static string PLACEHOLDER_PACKAGETEXT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PACKAGETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Password$.
        /// </summary>
        public static string PLACEHOLDER_PASSWORD {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $PasswordLink$.
        /// </summary>
        public static string PLACEHOLDER_PASSWORDLINK {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PASSWORDLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $PayLink$.
        /// </summary>
        public static string PLACEHOLDER_PAY_LINK {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PAY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $PinNumber$.
        /// </summary>
        public static string PLACEHOLDER_PINNUMBER {
            get {
                return ResourceManager.GetString("PLACEHOLDER_PINNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Recipient$.
        /// </summary>
        public static string PLACEHOLDER_Recepient_Email {
            get {
                return ResourceManager.GetString("PLACEHOLDER_Recepient_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RecipientFirstName$.
        /// </summary>
        public static string PLACEHOLDER_RECEPIENT_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_RECEPIENT_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RecipientFullName$.
        /// </summary>
        public static string PLACEHOLDER_RECEPIENT_FULL_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_RECEPIENT_FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RecipientFirstName$.
        /// </summary>
        public static string PLACEHOLDER_RECIPIENT_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_RECIPIENT_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RecipientFullName$.
        /// </summary>
        public static string PLACEHOLDER_RECIPIENT_FULL_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_RECIPIENT_FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RecipientsFirstName$.
        /// </summary>
        public static string PLACEHOLDER_Recipients_FIRST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_Recipients_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RecipientsLastName$.
        /// </summary>
        public static string PLACEHOLDER_Recipients_LAST_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_Recipients_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $RejectLink$.
        /// </summary>
        public static string PLACEHOLDER_REJECT_LINK {
            get {
                return ResourceManager.GetString("PLACEHOLDER_REJECT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $SenderFullName$.
        /// </summary>
        public static string PLACEHOLDER_SENDER_FULL_NAME {
            get {
                return ResourceManager.GetString("PLACEHOLDER_SENDER_FULL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Date$.
        /// </summary>
        public static string PLACEHOLDER_TRANSACTION_CANCELLED_ON {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSACTION_CANCELLED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $TransactionDate$.
        /// </summary>
        public static string PLACEHOLDER_TRANSACTION_DATE {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSACTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NewUserTransferAcceptLink$.
        /// </summary>
        public static string PLACEHOLDER_TRANSFER_ACCEPT_LINK {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSFER_ACCEPT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $Transfer_Amount$.
        /// </summary>
        public static string PLACEHOLDER_TRANSFER_AMOUNT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSFER_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $NewUserTransferRejectLink$.
        /// </summary>
        public static string PLACEHOLDER_TRANSFER_REJECT_LINK {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSFER_REJECT_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $TransferCount$.
        /// </summary>
        public static string PLACEHOLDER_TRANSFERCOUNT {
            get {
                return ResourceManager.GetString("PLACEHOLDER_TRANSFERCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelatedEnd.
        /// </summary>
        public static string RELATED_END {
            get {
                return ResourceManager.GetString("RELATED_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string SINGLE_SPACE {
            get {
                return ResourceManager.GetString("SINGLE_SPACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string STATUS_ACTIVE {
            get {
                return ResourceManager.GetString("STATUS_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string STATUS_INACTIVE {
            get {
                return ResourceManager.GetString("STATUS_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string STATUS_INVITED {
            get {
                return ResourceManager.GetString("STATUS_INVITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonRegistered.
        /// </summary>
        public static string STATUS_NON_REGISTERED {
            get {
                return ResourceManager.GetString("STATUS_NON_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered.
        /// </summary>
        public static string STATUS_REGISTERED {
            get {
                return ResourceManager.GetString("STATUS_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string STATUS_SUSPENDED {
            get {
                return ResourceManager.GetString("STATUS_SUSPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily_Blocked.
        /// </summary>
        public static string STATUS_TEMPORARILY_BLOCKED {
            get {
                return ResourceManager.GetString("STATUS_TEMPORARILY_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /temp/.
        /// </summary>
        public static string TEMP_FOLDER {
            get {
                return ResourceManager.GetString("TEMP_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About_Nooch.
        /// </summary>
        public static string TEMPLATE_ABOUT_NOOCH {
            get {
                return ResourceManager.GetString("TEMPLATE_ABOUT_NOOCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisputeResolvedMailTemplate.
        /// </summary>
        public static string TEMPLATE_DISPUTERESOLVED {
            get {
                return ResourceManager.GetString("TEMPLATE_DISPUTERESOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisputeReviewMailTemplate.
        /// </summary>
        public static string TEMPLATE_DISPUTEREVIEW {
            get {
                return ResourceManager.GetString("TEMPLATE_DISPUTEREVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite_Facebook_Member_Template.
        /// </summary>
        public static string TEMPLATE_FACEBOOK_INVITATION {
            get {
                return ResourceManager.GetString("TEMPLATE_FACEBOOK_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPasswordTemplate.
        /// </summary>
        public static string TEMPLATE_FORGOT_PASSWORD {
            get {
                return ResourceManager.GetString("TEMPLATE_FORGOT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForgotPinNoTemplate.
        /// </summary>
        public static string TEMPLATE_FORGOT_PINNUMBER {
            get {
                return ResourceManager.GetString("TEMPLATE_FORGOT_PINNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvitationTemplate.
        /// </summary>
        public static string TEMPLATE_INVITATION {
            get {
                return ResourceManager.GetString("TEMPLATE_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite_New_Member_Template.
        /// </summary>
        public static string TEMPLATE_NEW_MEMBER_INVITATION {
            get {
                return ResourceManager.GetString("TEMPLATE_NEW_MEMBER_INVITATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string TEMPLATE_PRIVACY {
            get {
                return ResourceManager.GetString("TEMPLATE_PRIVACY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistrationTemplate.
        /// </summary>
        public static string TEMPLATE_REGISTRATION {
            get {
                return ResourceManager.GetString("TEMPLATE_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string TEMPLATE_SECURITY {
            get {
                return ResourceManager.GetString("TEMPLATE_SECURITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string TEMPLATE_TERMS {
            get {
                return ResourceManager.GetString("TEMPLATE_TERMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $TransactionId$.
        /// </summary>
        public static string TRANSACTION_ID {
            get {
                return ResourceManager.GetString("TRANSACTION_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string TRANSACTION_TYPE_ALL {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        public static string TRANSACTION_TYPE_DEPOSIT {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_DEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation.
        /// </summary>
        public static string TRANSACTION_TYPE_DONATION {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_DONATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string TRANSACTION_TYPE_INVITE {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string TRANSACTION_TYPE_REQUEST {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string TRANSACTION_TYPE_TRANSFER {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_TRANSFER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string TRANSACTION_TYPE_WITHDRAW {
            get {
                return ResourceManager.GetString("TRANSACTION_TYPE_WITHDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&apos;#&apos; onclick=&apos;childWindow = window.open(&quot;$LINK_URL$&quot;);return false;&apos; $ATTRIBUTES$&gt;$LINK_TEXT$&lt;/a&gt;.
        /// </summary>
        public static string WINDOW_OPEN_HTML {
            get {
                return ResourceManager.GetString("WINDOW_OPEN_HTML", resourceCulture);
            }
        }
    }
}
